version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Create image for Alpine
          command: |
            docker build -t roquie/smalte:latest-alpine -f Dockerfile.alpine .
            docker push roquie/smalte:latest-alpine
      - run:
          name: Create image for Ubuntu
          command: |
            docker build -t roquie/smalte:latest-ubuntu -f Dockerfile.ubuntu .
            docker push roquie/smalte:latest-ubuntu
      - run:
          name: Create latest tag (by default Ubuntu)
          command: |
            docker tag roquie/smalte:latest-ubuntu roquie/smalte:latest
            docker push roquie/smalte:latest
